// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44HrsSK7FNvLx-k22hpWK4RzeW1QJZCw',
    appId: '1:979457116054:web:cd150454bd3dc640377fb7',
    messagingSenderId: '979457116054',
    projectId: 'sparkyflight-e3694',
    authDomain: 'sparkyflight-e3694.firebaseapp.com',
    storageBucket: 'sparkyflight-e3694.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc30hYFqvCi9RtM9GylfQ4mcnVtdzjxSk',
    appId: '1:979457116054:android:dc0b817b7a808c1d377fb7',
    messagingSenderId: '979457116054',
    projectId: 'sparkyflight-e3694',
    storageBucket: 'sparkyflight-e3694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsKf-R2Fg2sXS3dPxBIfeWrLHA-9lkcKo',
    appId: '1:979457116054:ios:559cfc1c7c848736377fb7',
    messagingSenderId: '979457116054',
    projectId: 'sparkyflight-e3694',
    storageBucket: 'sparkyflight-e3694.firebasestorage.app',
    androidClientId: '979457116054-1jork480fdnr2blrj0hnivdmje63e2pf.apps.googleusercontent.com',
    iosClientId: '979457116054-ou165qb61i5hh2jft8ppkq6so4ne02tr.apps.googleusercontent.com',
    iosBundleId: 'com.sparkyflight.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsKf-R2Fg2sXS3dPxBIfeWrLHA-9lkcKo',
    appId: '1:979457116054:ios:559cfc1c7c848736377fb7',
    messagingSenderId: '979457116054',
    projectId: 'sparkyflight-e3694',
    storageBucket: 'sparkyflight-e3694.firebasestorage.app',
    androidClientId: '979457116054-1jork480fdnr2blrj0hnivdmje63e2pf.apps.googleusercontent.com',
    iosClientId: '979457116054-ou165qb61i5hh2jft8ppkq6so4ne02tr.apps.googleusercontent.com',
    iosBundleId: 'com.sparkyflight.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzHQurJUpJ5gxvo-Mgby1_BTWIwiuNxiE',
    appId: '1:979457116054:web:de7cbb076fdc8264377fb7',
    messagingSenderId: '979457116054',
    projectId: 'sparkyflight-e3694',
    authDomain: 'sparkyflight-e3694.firebaseapp.com',
    storageBucket: 'sparkyflight-e3694.firebasestorage.app',
  );

}